name: Update DACS Website

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-dacs:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout website repository
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Update DACS submodule
        run: |
          git submodule update --remote --recursive

      - name: Show changes
        run: |
          git status
          git diff

      - name: Commit submodule update
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add dacs
          git commit -m "Update DACS content" || echo "No DACS updates"

      - name: Push update
        run: |
          git push origin master
